default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: postgres
      password: password
      host:     localhost  
      #template: template0
      port: 5432
      
development:
  <<: *default
  database: app_development
  
test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production